In [2]:
pip install numpy # Importing numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [3]:
pip install pandas # Importing pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd
import numpy as np

In [6]:
data = {"names":["santhosh","siva","rajee","neha","apuroop","surya","madhuri"],"age":[22,22,43,21,22,21,22],"location":["KKD"]*7} # Data Preparation Data should be dict key-value pair where the key is list datatype

In [7]:
df = pd.DataFrame(data) # Creation of dataframe using pandas
print(df)

      names  age location
0  santhosh   22      KKD
1      siva   22      KKD
2     rajee   43      KKD
3      neha   21      KKD
4   apuroop   22      KKD
5     surya   21      KKD
6   madhuri   22      KKD

In [8]:
df.head() # prints first 5 entries of the dataframe

      names  age location
0  santhosh   22      KKD
1      siva   22      KKD
2     rajee   43      KKD
3      neha   21      KKD
4   apuroop   22      KKD

In [9]:
df_head = df.head() # returns first 5 entries of the dataframe
print(df_head)

      names  age location
0  santhosh   22      KKD
1      siva   22      KKD
2     rajee   43      KKD
3      neha   21      KKD
4   apuroop   22      KKD

In [10]:
df.tail() # prints the last 5 entries of the dataframe

     names  age location
2    rajee   43      KKD
3     neha   21      KKD
4  apuroop   22      KKD
5    surya   21      KKD
6  madhuri   22      KKD

In [11]:
df_tail = df.tail() # returns the last 5 entries of the dataframe
print(df_tail)

     names  age location
2    rajee   43      KKD
3     neha   21      KKD
4  apuroop   22      KKD
5    surya   21      KKD
6  madhuri   22      KKD

In [12]:
# df.head() and df.tail() both will return and print thier respective rows of an dataframe

In [14]:
df.info() # returns the info of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   names     7 non-null      object
 1   age       7 non-null      int64
 2   location  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [15]:
df.describe() # returns the arthematic related report of the dataset for numerical columns in the dataset

             age
count   7.000000
mean   24.714286
std     8.077010
min    21.000000
25%    21.500000
50%    22.000000
75%    22.000000
max    43.000000

In [16]:
df["age"] # Acessing the columns of an dataframe can be done using the key's of the data

0    22
1    22
2    43
3    21
4    22
5    21
6    22
Name: age, dtype: int64

In [17]:
df[df["age"]<25] # Conditional accesing can be also done using arthimatic

      names  age location
0  santhosh   22      KKD
1      siva   22      KKD
3      neha   21      KKD
4   apuroop   22      KKD
5     surya   21      KKD
6   madhuri   22      KKD

In [23]:
df["education"]="B.TECH" # creation of an column in the dataframe
print(df)

      names  age location education
0  santhosh   22      KKD    B.TECH
1      siva   22      KKD    B.TECH
2     rajee   43      KKD    B.TECH
3      neha   21      KKD    B.TECH
4   apuroop   22      KKD    B.TECH
5     surya   21      KKD    B.TECH
6   madhuri   22      KKD    B.TECH

In [25]:
# Question change the education of the girl named neha to MBA
for i in range(len(df)) :
  if df["names"][i]=="neha":
    df["education"][i]= "MBA"

print(df)

      names  age location education
0  santhosh   22      KKD    B.TECH
1      siva   22      KKD    B.TECH
2     rajee   43      KKD    B.TECH
3      neha   21      KKD       MBA
4   apuroop   22      KKD    B.TECH
5     surya   21      KKD    B.TECH
6   madhuri   22      KKD    B.TECH

/tmp/ipykernel_726/360269712.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["education"][i]= "MBA"
/tmp/ipykernel_726/360269712.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["education"][i]= "MBA"

In [26]:
# Before training the model with the data should be duplicated and null values should be removed

In [28]:
# case 1 (null values)
df = df.dropna() # Used to remove the null values
print(df)

      names  age location education
0  santhosh   22      KKD    B.TECH
1      siva   22      KKD    B.TECH
2     rajee   43      KKD    B.TECH
3      neha   21      KKD       MBA
4   apuroop   22      KKD    B.TECH
5     surya   21      KKD    B.TECH
6   madhuri   22      KKD    B.TECH

In [29]:
# case 1 (null values)
df = df.fillna(1) # you can fill the null values with certain values like mean , median , mode etc
print(df)

      names  age location education
0  santhosh   22      KKD    B.TECH
1      siva   22      KKD    B.TECH
2     rajee   43      KKD    B.TECH
3      neha   21      KKD       MBA
4   apuroop   22      KKD    B.TECH
5     surya   21      KKD    B.TECH
6   madhuri   22      KKD    B.TECH

In [30]:
#case 2(duplicates)
df = df.drop_duplicates() # used to remove the duplicates
print(df)

      names  age location education
0  santhosh   22      KKD    B.TECH
1      siva   22      KKD    B.TECH
2     rajee   43      KKD    B.TECH
3      neha   21      KKD       MBA
4   apuroop   22      KKD    B.TECH
5     surya   21      KKD    B.TECH
6   madhuri   22      KKD    B.TECH

In [31]:
df.to_csv("sample.csv") # to convert df to .csv file

In [33]:
df_csv = pd.read_csv("sample.csv") # Read data from .csv file and converts it into DataFrame
print(df_csv)

   Unnamed: 0     names  age location education
0           0  santhosh   22      KKD    B.TECH
1           1      siva   22      KKD    B.TECH
2           2     rajee   43      KKD    B.TECH
3           3      neha   21      KKD       MBA
4           4   apuroop   22      KKD    B.TECH
5           5     surya   21      KKD    B.TECH
6           6   madhuri   22      KKD    B.TECH